#!/bin/bash
# comparative-research.sh — Run deep research across ChatGPT, Gemini, and Claude apps
# Usage: ./comparative-research.sh "research topic" [output-dir]

set -euo pipefail

TOPIC="$1"
OUTPUT_DIR="${2:-$(pwd)/comparative-research-$(date +%Y%m%d-%H%M%S)}"

echo "🔬 Starting Comparative Research: $TOPIC"
echo "📁 Output directory: $OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"

# Step 1: Generate research prompt using ChatGPT
echo "🤖 Step 1: Generating research prompt via ChatGPT..."
PROMPT_FILE="$OUTPUT_DIR/research-prompt.md"

sessions_spawn \
    agentId="operator" \
    task="Use ChatGPT app to generate a comprehensive deep research prompt for this topic: '$TOPIC'

Instructions for ChatGPT:
- Create a detailed research prompt that will produce a thorough, well-sourced analysis
- The prompt should request: executive summary, key findings, detailed analysis, sources, methodology
- Ask for specific citations and references
- Request coverage of multiple perspectives and current developments
- Make it suitable for academic/professional research
- Output length should target 4000-6000 words

Save the generated prompt to: $PROMPT_FILE

Then take a screenshot of the ChatGPT response and save to $OUTPUT_DIR/chatgpt-prompt-generation.png" \
    cleanup="keep" \
    label="prompt-generation"

echo "⏳ Waiting for prompt generation to complete..."
sleep 30  # Give time for operator to work

# Wait for prompt file to exist
while [ ! -f "$PROMPT_FILE" ]; do
    echo "   Waiting for prompt file..."
    sleep 10
done

echo "✅ Research prompt generated!"
cat "$PROMPT_FILE"

# Step 2: Run research on ChatGPT
echo ""
echo "🤖 Step 2: Running research on ChatGPT..."
sessions_spawn \
    agentId="operator" \
    task="Use ChatGPT app to run the research prompt from: $PROMPT_FILE

Instructions:
1. Open ChatGPT app, start fresh conversation
2. Paste the research prompt and submit
3. Wait for complete response
4. Copy the full response and save to: $OUTPUT_DIR/chatgpt-report.md
5. Take screenshot of the response and save to: $OUTPUT_DIR/chatgpt-report.png

Topic: $TOPIC" \
    cleanup="keep" \
    label="chatgpt-research"

# Step 3: Run research on Gemini (browser automation)
echo ""
echo "🌟 Step 3: Running research on Gemini..."
sessions_spawn \
    agentId="operator" \
    task="Use browser automation to run the research prompt on Gemini web interface.

Instructions:
1. Open https://gemini.google.com in browser (openclaw profile)
2. Sign in with cdboteea@gmail.com if needed
3. Paste the research prompt from: $PROMPT_FILE
4. Submit and wait for complete response
5. Copy the full response and save to: $OUTPUT_DIR/gemini-report.md
6. Take screenshot and save to: $OUTPUT_DIR/gemini-report.png

Topic: $TOPIC" \
    cleanup="keep" \
    label="gemini-research"

# Step 4: Run research on Claude app (if available)
echo ""
echo "🧠 Step 4: Running research on Claude app..."
sessions_spawn \
    agentId="operator" \
    task="Use Claude app to run the research prompt from: $PROMPT_FILE

Instructions:
1. Open Claude app, start fresh conversation  
2. Paste the research prompt and submit
3. Wait for complete response
4. Copy the full response and save to: $OUTPUT_DIR/claude-report.md
5. Take screenshot and save to: $OUTPUT_DIR/claude-report.png

Topic: $TOPIC" \
    cleanup="keep" \
    label="claude-research"

# Step 5: Generate comparison analysis
echo ""
echo "📊 Step 5: Generating comparison analysis..."
sleep 60  # Give time for all research to complete

sessions_spawn \
    agentId="research" \
    task="Analyze and compare the research reports generated by different AI models.

Files to analyze:
- ChatGPT: $OUTPUT_DIR/chatgpt-report.md
- Gemini: $OUTPUT_DIR/gemini-report.md  
- Claude: $OUTPUT_DIR/claude-report.md

Create a comprehensive comparison report covering:
1. Content quality and depth
2. Source quality and citations
3. Unique insights from each model
4. Factual accuracy assessment
5. Writing style and structure
6. Strengths and weaknesses of each
7. Overall recommendations

Save the comparison to: $OUTPUT_DIR/comparison-analysis.md

Topic: $TOPIC" \
    cleanup="keep" \
    label="comparison-analysis"

echo ""
echo "🎉 Comparative research pipeline initiated!"
echo "📁 All outputs will be saved to: $OUTPUT_DIR"
echo ""
echo "Monitor progress with:"
echo "  sessions_list"
echo ""
echo "Results will include:"
echo "  - research-prompt.md (generated prompt)"
echo "  - chatgpt-report.md (ChatGPT analysis)"  
echo "  - gemini-report.md (Gemini analysis)"
echo "  - claude-report.md (Claude analysis)"
echo "  - comparison-analysis.md (comparative analysis)"
echo "  - Screenshots from each platform"