#!/usr/bin/env python3
"""
Google Shared Drive Setup for Idea Database
Helps configure shared drive to resolve service account storage quota issues
"""

import os
import sys
import asyncio
import json
from pathlib import Path

# Add src to path for imports
sys.path.append("/app/src")

from drive_client import DriveClient

async def main():
    print("🚀 Google Shared Drive Setup for Idea Database")
    print("=" * 50)
    
    # Load configuration
    config = {
        'drive': {
            'service_account_path': '/app/config/drive_service_account.json',
            'folder_name': 'idea-database-attachments'
        },
        'email': {
            'intake_email': os.getenv('INTAKE_EMAIL', 'ideaseea@gmail.com')
        }
    }
    
    # Check if running in Docker or local
    if not os.path.exists(config['drive']['service_account_path']):
        # Try local path
        local_path = Path(__file__).parent / "gmail_credentials" / "drive_service_account.json"
        if local_path.exists():
            config['drive']['service_account_path'] = str(local_path)
        else:
            print("❌ Drive service account file not found!")
            print(f"   Expected: {config['drive']['service_account_path']}")
            print(f"   Or: {local_path}")
            return False
    
    print(f"✅ Found service account: {config['drive']['service_account_path']}")
    
    # Initialize Drive client
    drive_client = DriveClient(config)
    
    if not drive_client.has_credentials():
        print("❌ Failed to initialize Drive client")
        return False
    
    print("✅ Drive client initialized")
    
    # List existing shared drives
    print("\n📂 Checking for existing shared drives...")
    shared_drives = await drive_client.list_shared_drives()
    
    if shared_drives:
        print(f"Found {len(shared_drives)} shared drives:")
        for i, drive in enumerate(shared_drives):
            print(f"  {i+1}. {drive['name']} (ID: {drive['id']})")
        
        print("\nOptions:")
        print("1. Use existing shared drive")
        print("2. Create new shared drive")
        choice = input("Choose option (1 or 2): ").strip()
        
        if choice == "1":
            drive_index = int(input(f"Select drive (1-{len(shared_drives)}): ")) - 1
            if 0 <= drive_index < len(shared_drives):
                selected_drive = shared_drives[drive_index]
                shared_drive_id = selected_drive['id']
                shared_drive_name = selected_drive['name']
                print(f"✅ Selected: {shared_drive_name}")
            else:
                print("❌ Invalid selection")
                return False
        else:
            # Create new shared drive
            drive_name = input("Enter name for new shared drive [idea-database-storage]: ").strip()
            if not drive_name:
                drive_name = "idea-database-storage"
            
            print(f"🔄 Creating shared drive: {drive_name}")
            shared_drive_id = await drive_client.create_shared_drive(drive_name)
            
            if not shared_drive_id:
                print("❌ Failed to create shared drive")
                print("   Note: You may need admin permissions or Google Workspace")
                return False
            
            shared_drive_name = drive_name
            print(f"✅ Created shared drive: {shared_drive_name} (ID: {shared_drive_id})")
    
    else:
        print("No existing shared drives found.")
        drive_name = input("Enter name for new shared drive [idea-database-storage]: ").strip()
        if not drive_name:
            drive_name = "idea-database-storage"
        
        print(f"🔄 Creating shared drive: {drive_name}")
        shared_drive_id = await drive_client.create_shared_drive(drive_name)
        
        if not shared_drive_id:
            print("❌ Failed to create shared drive")
            print("   Note: You may need admin permissions or Google Workspace")
            return False
        
        shared_drive_name = drive_name
        print(f"✅ Created shared drive: {shared_drive_name} (ID: {shared_drive_id})")
    
    # Update environment configuration
    print("\n🔧 Configuration:")
    print(f"DRIVE_USE_SHARED=true")
    print(f"DRIVE_SHARED_DRIVE_ID={shared_drive_id}")
    
    # Create .env file with the configuration
    env_file = Path(__file__).parent / ".env.shared_drive"
    with open(env_file, 'w') as f:
        f.write(f"# Google Shared Drive Configuration\n")
        f.write(f"# Generated by setup_shared_drive.py\n")
        f.write(f"DRIVE_USE_SHARED=true\n")
        f.write(f"DRIVE_SHARED_DRIVE_ID={shared_drive_id}\n")
        f.write(f"# Shared drive name: {shared_drive_name}\n")
    
    print(f"✅ Configuration saved to: {env_file}")
    
    # Update docker-compose.yml
    print("\n📝 Next steps:")
    print("1. Add these environment variables to your docker-compose.yml:")
    print("   ```")
    print("   environment:")
    print("     - DRIVE_USE_SHARED=true")
    print(f"     - DRIVE_SHARED_DRIVE_ID={shared_drive_id}")
    print("   ```")
    print()
    print("2. Restart the email processor service:")
    print("   ```")
    print("   docker-compose restart email_processor")
    print("   ```")
    print()
    print("3. Test the Drive upload:")
    print("   ```")
    print("   curl -X POST -F \"file=@test.txt\" http://localhost:3003/drive/upload")
    print("   ```")
    
    return True

if __name__ == "__main__":
    success = asyncio.run(main())
    sys.exit(0 if success else 1) 